[project]
name = "elith-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.120.2",
    "marimo>=0.23.15",
    "numpy>=2.5.1",
    "pydantic-ai-slim>=2.20.0",
    "scipy>=1.18.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]
